name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Go to api directory
      run: cd api
    - name: change to nightly
      run: rustup default nightly
    - name: Build
      run: cargo build --manifest-path api/Cargo.toml --verbose
    - name: Run tests
      run: cargo test --manifest-path api/Cargo.toml --verbose
